from setuptools import setup, find_packages
from __version__ import __version__


setup(
    name="aloception",
    author="Visual Behavior",
    version=__version__,
    description="Aloception is a set of package for computer vision: aloscene, alodataset, alonet.",
    packages=find_packages(include=["aloscene", "aloscene.*", "alodataset", "alodataset.*", "alonet", "alonet.*"]),
    url="https://visualbehavior.ai/",
    download_url="https://github.com/Visual-Behavior/aloception-oss",
    install_requires=[
        "pycocotools==2.0.8",
        "PyYAML==6.0.2",
        "chardet==4.0.0",
        "idna==2.10",
        "numpy==2.2.2",
        "matplotlib==3.10.1",
        "scipy==1.15.2",
        "more_itertools==8.8.0",
        "opencv-python==4.11.0.86",
        "python-dateutil==2.8.2",
        "urllib3==1.26.6",
        "protobuf==4.21.12",
        "tqdm==4.62.3",
        "captum==0.4.0",
        "setuptools==59.5.0",
        "safetensors==0.5.3",
        "tensorboard==2.19.0",
        "wandb==0.17.9",
        "onnx==1.12.0",
        "onnx-graphsurgeon==0.3.14",
        "onnxsim==0.4.36",
        "pycuda==2025.1",
        "tensorrt==10.10.0.31",
    ],
    setup_requires=[],
    license_files=["LICENSE"],
    keywords=["artificial intelligence", "computer vision"],
    classifiers=["Programming Language :: Python", "Topic :: Scientific/Engineering :: Artificial Intelligence"],
)
